### ISSUE TITLE
Music Player

### ISSUE THREAD

**Issue by matiaseo** [matiaseo/SpottedFly#1]
Create the Music Player component as shown in the picture below:

Besides the normal buttons that a player should have we also have some other actions or elements such as a usage of the sideBarItem on the left side of the player (maybe we should rename this to something else) but it shows the image of the artists/album name of the song and name of the artist, next to it a button to "like" or add to our library.

On the rightside we have the "You are listening View" button (which seems like we won't work with) 
The queue button and the Devices button.
Lastly the volume controller.

![Image](https://github.com/matiaseo/SpottedFly/assets/48894486/d1e2706c-7a19-4450-acda-1396d3c89a2a)

**Comment by MatiasPastori** [comment]
There is already a placeholder and some minimum work done for this issue @EzequielZarza

As it was discussed in our last Ignite meeting we know now that:

- Deezer api call for album provides us a list of tracks, and each of these tracks (or at least the particular track API call) brings a preview field with a link to the actual .mp3 file, from which we can stream the music.

**Comment by MatiasPastori** [comment]
Music player is for now and for the sake of keeping it simple in the first sessions, a child of the same parent of the album (if not the album itself) so... we are not routing for now, thats for future sessions.

**Comment by MatiasPastori** [comment]
This was completed for the MVP. Might add a relation or link in a future issue to this old one when we start implementing routing and context.
